# Generated by Django 5.1.2 on 2024-10-24 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0006_historypromo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historypromo',
            name='description',
        ),
        migrations.RemoveField(
            model_name='historypromo',
            name='discount_percentage',
        ),
        migrations.RemoveField(
            model_name='historypromo',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='historypromo',
            name='promo_code',
        ),
        migrations.RemoveField(
            model_name='historypromo',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='historypromo',
            name='title',
        ),
        migrations.AddField(
            model_name='historypromo',
            name='promo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='promo.promo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historypromo',
            name='redeem_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
