# Generated by Django 5.1.2 on 2024-10-24 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0006_historypromo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historypromo',
            name='description',
            field=models.TextField(default='No description'),
        ),
        migrations.AlterField(
            model_name='historypromo',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
