# Generated by Django 5.1.2 on 2024-10-27 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0007_alter_historypromo_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoryPromo',
        ),
        migrations.RemoveField(
            model_name='promo',
            name='image',
        ),
        migrations.DeleteModel(
            name='RedeemedPromo',
        ),
    ]
