# Generated by Django 5.1.2 on 2024-10-24 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0007_remove_historypromo_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historypromo',
            name='promo',
        ),
        migrations.RemoveField(
            model_name='historypromo',
            name='redeem_count',
        ),
        migrations.AddField(
            model_name='historypromo',
            name='description',
            field=models.TextField(default='No description'),
        ),
        migrations.AddField(
            model_name='historypromo',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='historypromo',
            name='end_date',
            field=models.DateField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historypromo',
            name='promo_code',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historypromo',
            name='start_date',
            field=models.DateField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historypromo',
            name='title',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
