# Generated by Django 5.1.2 on 2024-10-26 21:50

import django.utils.timezone
from django.db import migrations, models
# Generated by Django 5.1.2 on 2024-10-27 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0007_alter_historypromo_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoryPromo',
        ),
        migrations.RemoveField(
            model_name='promo',
            name='image',
        ),
        migrations.AlterField(
            model_name='promo',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='RedeemedPromo',
        ),
    ]
