# Generated by Django 5.1.2 on 2024-10-22 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_remove_forum_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
