# Generated by Django 5.1 on 2024-10-26 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimony', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimony',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
