# Generated by Django 5.1.2 on 2024-10-15 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_alter_category_options_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
    ]
