# Generated by Django 5.1.2 on 2024-10-16 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_remove_category_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='category',
            new_name='categories',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='instagram_account',
            new_name='social_media',
        ),
        migrations.AlterField(
            model_name='store',
            name='contact_number',
            field=models.CharField(max_length=16),
        ),
    ]
