# Generated by Django 5.1.2 on 2024-10-16 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_rename_category_store_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=31, unique=True),
        ),
    ]
