# Generated by Django 5.1 on 2024-10-23 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_store_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='categories',
        ),
    ]
