# Generated by Django 5.1 on 2024-10-23 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0007_remove_store_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='categories',
            field=models.ManyToManyField(to='stores.category'),
        ),
    ]
